version: "2"

        
networks:
  monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/29            # 
          gateway: 172.20.0.1              #     
          ip_range: 172.20.0.0/29          # Network .0; gateway .1 ; grafana .2; influxdb .3 ;  nas_telegraf .4; fbx_telegraf .5; N/A .6 ; Broadcast .7

services:

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        hostname: grafana

        mac_address: d2:ca:ab:cd:00:02
        networks:
           monitoring:
               ipv4_address: 172.20.0.2 

        mem_limit: 75M
        volumes:
            - "/volume1/docker/monitoring/grafana/data:/var/lib/grafana"
        user: "1026"
        ports:
            - 3000:3000
        restart: unless-stopped

    influxdb:
        image: influxdb:latest
        container_name: influxdb
        hostname: influxdb

        mac_address: d2:ca:ab:cd:00:03
        networks:
           monitoring:
               ipv4_address: 172.20.0.3 

        environment:
            - INFLUXDB_DB=nas_telegraf
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
            - INFLUXDB_USER=nas_telegraf
            - INFLUXDB_USER_PASSWORD=nas_telegraf
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            
        mem_limit: 750M  
        volumes:
            - "/volume1/docker/monitoring/influxdb/data:/var/lib/influxdb"
        ports:
            - 8086:8086
        restart: unless-stopped

    nas_telegraf:
        image: telegraf:latest
        container_name: nas_telegraf
        hostname: nas_telegraf

        mac_address: d2:ca:ab:cd:00:04
        networks:
           monitoring:
               ipv4_address: 172.20.0.4
        environment:
            - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin:/usr/local:/usr/src
            - TZ=CET
        mem_limit: 75M 
        volumes:
            - "/volume1/docker/monitoring/nas_telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
            - "/proc:/host/proc:ro"
            - "/usr/share/snmp/mibs:/usr/share/snmp/mibs:ro"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
            - 8125:8125/udp
            - 8092:8092/udp
            - 8094:8094
        restart: unless-stopped   
        
    fbx_telegraf:
        image: telegraf:latest
        container_name: fbx_telegraf
        hostname: fbx_telegraf

        mac_address: d2:ca:ab:cd:00:05
        networks:
           monitoring:
               ipv4_address: 172.20.0.5
        environment:
            - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin:/usr/local:/usr/src
            - TZ=CET
        mem_limit: 75M 
        volumes:
            - "/volume1/docker/monitoring/fbx_telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
            # pour le fichier de commande python d'acces a la freebox, 
            # pour le fichier de commande python, 
            # pour le fichier get-pip.py (install module pip puis requests
            - "/volume1/docker/monitoring/fbx_telegraf/py:/usr/local/py:ro"  
            # pour le fichier log si on le met en place
            - "/volume1/docker/monitoring/fbx_telegraf/log:/usr/local/log"
        ports:
            - 9125:8125/udp
            - 9092:8092/udp
            - 9094:8094
        restart: unless-stopped         